name: curl

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/curl.yml'
      - 'ports/curl/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/curl.yml'
      - 'ports/curl/**'

jobs:

  build:
    runs-on: self-hosted
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, 'curl'))
    steps:
    - name: Checkout build-files
      uses: actions/checkout@v4
      with:
        path: build-files

    - name: Checkout curl
      uses: actions/checkout@v4
      with:
        repository: curl/curl
        path: curl
        ref: 7eb8c048470ed2cc14dca75be9c1cdae7ac8498b

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Pull build environment
      run: |
        docker pull ghcr.io/qnx-ports/sdp800-build-env:latest

    - name: Build curl
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/qnx-ports/sdp800-build-env:latest
        options: -v ${{ github.workspace }}:/home/runner/workspace -e MAKEFLAGS=${{ env.MAKEFLAGS }}
        shell: bash
        run: |
          source ~/qnx/800/qnxsdp-env.sh
          cd ~/workspace
          cd build-files/ports/curl
          sed -i "s/qnx710/qnx\/710/" setup
          sed -i "s/qnx800/qnx\/800/" setup
          SOURCE_ROOT="../../../curl" ./mkrelease.sh